Timestamp: 24/03/22 12:28:05    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Repositories\inv_repo.py    -    ErrType: <class 'AttributeError'>    -    ErrTraceback: <frame at 0x0000027D779D7650, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Repositories\\inv_repo.py', line 141, code generate_xls>    -    Error occurred while writing to xlsx file!
Timestamp: 24/03/22 12:33:09    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Repositories\inv_repo.py    -    ErrType: <class 'TypeError'>    -    ErrTraceback: <frame at 0x0000010D1BA04FA0, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Repositories\\inv_repo.py', line 159, code generate_xls>    -    Error occurred while writing to xlsx file!
Timestamp: 24/03/22 12:36:47    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Repositories\inv_repo.py    -    ErrType: <class 'xlsxwriter.exceptions.FileCreateError'>    -    ErrTraceback: <frame at 0x0000026ABF844070, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Repositories\\inv_repo.py', line 167, code generate_xls>    -    Error occurred while writing to xlsx file!
Timestamp: 25/03/22 13:28:40    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\sales\transaction_mgmt.py    -    ErrType: <class 'TypeError'>    -    ErrTraceback: <frame at 0x000002881443EA40, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\sales\\transaction_mgmt.py', line 138, code save_transact>    -    Error saving transactions!
Timestamp: 25/03/22 13:38:08    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\sales\transaction_mgmt.py    -    ErrType: <class 'KeyError'>    -    ErrTraceback: <frame at 0x00000235C1DD49E0, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\sales\\transaction_mgmt.py', line 166, code load_transact>    -    Error Loading transactions!
Timestamp: 25/03/22 13:39:03    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\sales\transaction_mgmt.py    -    ErrType: <class 'TypeError'>    -    ErrTraceback: <frame at 0x000001D5401A9B90, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\sales\\transaction_mgmt.py', line 166, code load_transact>    -    Error Loading transactions!
