Timestamp: 24/03/22 12:28:05    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Repositories\inv_repo.py    -    ErrType: <class 'AttributeError'>    -    ErrTraceback: <frame at 0x0000027D779D7650, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Repositories\\inv_repo.py', line 141, code generate_xls>    -    Error occurred while writing to xlsx file!
Timestamp: 24/03/22 12:33:09    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Repositories\inv_repo.py    -    ErrType: <class 'TypeError'>    -    ErrTraceback: <frame at 0x0000010D1BA04FA0, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Repositories\\inv_repo.py', line 159, code generate_xls>    -    Error occurred while writing to xlsx file!
Timestamp: 24/03/22 12:36:47    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Repositories\inv_repo.py    -    ErrType: <class 'xlsxwriter.exceptions.FileCreateError'>    -    ErrTraceback: <frame at 0x0000026ABF844070, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Repositories\\inv_repo.py', line 167, code generate_xls>    -    Error occurred while writing to xlsx file!
Timestamp: 25/03/22 13:28:40    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\sales\transaction_mgmt.py    -    ErrType: <class 'TypeError'>    -    ErrTraceback: <frame at 0x000002881443EA40, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\sales\\transaction_mgmt.py', line 138, code save_transact>    -    Error saving transactions!
Timestamp: 25/03/22 13:38:08    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\sales\transaction_mgmt.py    -    ErrType: <class 'KeyError'>    -    ErrTraceback: <frame at 0x00000235C1DD49E0, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\sales\\transaction_mgmt.py', line 166, code load_transact>    -    Error Loading transactions!
Timestamp: 25/03/22 13:39:03    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\sales\transaction_mgmt.py    -    ErrType: <class 'TypeError'>    -    ErrTraceback: <frame at 0x000001D5401A9B90, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\sales\\transaction_mgmt.py', line 166, code load_transact>    -    Error Loading transactions!
Timestamp: 25/03/22 13:58:10    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\warehousing\product_mgmt.py    -    ErrType: <class 'AttributeError'>    -    ErrTraceback: <frame at 0x000001A541389F20, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\warehousing\\product_mgmt.py', line 210, code load_products>    -    Error loading products!
Timestamp: 25/03/22 13:58:22    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\warehousing\product_mgmt.py    -    ErrType: <class 'AttributeError'>    -    ErrTraceback: <frame at 0x00000193540D4450, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\warehousing\\product_mgmt.py', line 210, code load_products>    -    Error loading products!
Timestamp: 25/03/22 13:58:46    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\warehousing\product_mgmt.py    -    ErrType: <class 'AttributeError'>    -    ErrTraceback: <frame at 0x0000027CFE0FC730, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\warehousing\\product_mgmt.py', line 210, code load_products>    -    Error loading products!
Timestamp: 25/03/22 14:00:34    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\warehousing\product_mgmt.py    -    ErrType: <class 'AttributeError'>    -    ErrTraceback: <frame at 0x00000211C8A30700, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\warehousing\\product_mgmt.py', line 210, code load_products>    -    Error loading products!
Timestamp: 25/03/22 14:01:57    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\warehousing\product_mgmt.py    -    ErrType: <class 'AttributeError'>    -    ErrTraceback: <frame at 0x0000025B7AF21D80, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\warehousing\\product_mgmt.py', line 210, code load_products>    -    Error loading products!
Timestamp: 25/03/22 14:02:01    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\warehousing\product_mgmt.py    -    ErrType: <class 'AttributeError'>    -    ErrTraceback: <frame at 0x000001F7EF552990, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\warehousing\\product_mgmt.py', line 210, code load_products>    -    Error loading products!
Timestamp: 25/03/22 14:37:02    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\sales\inv_mgmt.py    -    ErrType: <class 'TypeError'>    -    ErrTraceback: <frame at 0x000001519D56B260, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\sales\\inv_mgmt.py', line 188, code save_inv>    -    Error saving invoices!
Timestamp: 25/03/22 14:38:27    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\sales\inv_mgmt.py    -    ErrType: <class 'TypeError'>    -    ErrTraceback: <frame at 0x000002555CE28BD0, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\sales\\inv_mgmt.py', line 188, code save_inv>    -    Error saving invoices!
Timestamp: 25/03/22 14:39:11    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\sales\inv_mgmt.py    -    ErrType: <class 'TypeError'>    -    ErrTraceback: <frame at 0x00000165CFE3F560, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\sales\\inv_mgmt.py', line 188, code save_inv>    -    Error saving invoices!
Timestamp: 25/03/22 14:42:35    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\sales\transaction_mgmt.py    -    ErrType: <class 'ValueError'>    -    ErrTraceback: <frame at 0x00000208EB83D970, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\sales\\transaction_mgmt.py', line 170, code load_transact>    -    Error Loading transactions!
Timestamp: 25/03/22 14:42:35    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\sales\inv_mgmt.py    -    ErrType: <class 'TypeError'>    -    ErrTraceback: <frame at 0x00000208EB8C5E50, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\sales\\inv_mgmt.py', line 188, code save_inv>    -    Error saving invoices!
Timestamp: 25/03/22 14:45:17    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\sales\transaction_mgmt.py    -    ErrType: <class 'ValueError'>    -    ErrTraceback: <frame at 0x0000017ACBAD63B0, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\sales\\transaction_mgmt.py', line 170, code load_transact>    -    Error Loading transactions!
Timestamp: 25/03/22 14:45:17    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\sales\inv_mgmt.py    -    ErrType: <class 'TypeError'>    -    ErrTraceback: <frame at 0x0000017ACD9B2800, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\sales\\inv_mgmt.py', line 188, code save_inv>    -    Error saving invoices!
