Timestamp: 24/03/22 12:28:05    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Repositories\inv_repo.py    -    ErrType: <class 'AttributeError'>    -    ErrTraceback: <frame at 0x0000027D779D7650, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Repositories\\inv_repo.py', line 141, code generate_xls>    -    Error occurred while writing to xlsx file!
Timestamp: 24/03/22 12:33:09    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Repositories\inv_repo.py    -    ErrType: <class 'TypeError'>    -    ErrTraceback: <frame at 0x0000010D1BA04FA0, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Repositories\\inv_repo.py', line 159, code generate_xls>    -    Error occurred while writing to xlsx file!
Timestamp: 24/03/22 12:36:47    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Repositories\inv_repo.py    -    ErrType: <class 'xlsxwriter.exceptions.FileCreateError'>    -    ErrTraceback: <frame at 0x0000026ABF844070, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Repositories\\inv_repo.py', line 167, code generate_xls>    -    Error occurred while writing to xlsx file!
